// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Wormix.Searching;
using Content.Client.Actions;
using Content.Client.Stylesheets;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using System.Linq;
using System.Linq.Expressions;
using System.Numerics;
using System.Xml.Linq;
using static Content.Shared._Wormix.ChatsanPlus.ChatsanPlusSystem;
using static Content.Shared._Wormix.CCVar.CCVar;
using Content.Shared.Kitchen;
using Content.Shared._Wormix.CCVar;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ChatsanPlusTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private string _searchText = "";
    private List<Short> _shorts = new List<Short>();
    private bool _changed = false;




    public ChatsanPlusTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _shorts = Deserialize(_cfg.GetCVar(ShortArchive));

        if (_shorts.Count == 0)
        {
            _shorts = BasicShorts;
            _cfg.SetCVar(ShortArchive, Serialize(BasicShorts));
        }

        DefaultButton.Disabled = true;
        ApplyButton.Disabled = true;

        SearchInput.OnTextChanged += _ =>
        {
            _searchText = SearchInput.Text.TrimStart()
                                        .Replace("ё", "е");

            PopulateShorts();
        };

        DefaultButton.OnPressed += args =>
        {

            DefaultButton.Disabled = true;
            ApplyButton.Disabled = true;

            _changed = false;

            _cfg.SetCVar(ShortArchive, Serialize(BasicShorts));
            _shorts = BasicShorts;
            PopulateShorts();
        };

        ApplyButton.OnPressed += args =>
        {
            _changed = false;

            var toSave = new List<Short>();

            foreach (var _short in _shorts)
            {
                if (_short.Trigger != string.Empty && _short.Reaction != string.Empty)
                {
                    toSave.Add(_short);
                }
            }

            DefaultButton.Disabled = true;
            ApplyButton.Disabled = true;

            _cfg.SetCVar(ShortArchive, Serialize(toSave));
            _cfg.SaveToFile();
        };

        AddNewButton.OnPressed += args =>
        {
            _changed = true;
            AddShort(new Short()
            {
                Reaction = "",
                Trigger = "",
                Channel = ChatSelectChannel.Local
            });
        };

        PopulateShorts();
    }

    public void RemoveShort(int index)
    {
        _shorts.RemoveAt(index);
        PopulateShorts();
        _changed = true;

        DefaultButton.Disabled = false;
        ApplyButton.Disabled = false;
    }

    public void EditTrigerShort(string newTrigger, int index)
    {
        _shorts[index].Trigger = newTrigger;
        _changed = true;

        DefaultButton.Disabled = false;
        ApplyButton.Disabled = false;
    }

    public void EditReactionShort(string newReaction, int index)
    {
        _shorts[index].Reaction = newReaction;
        _changed = true;

        DefaultButton.Disabled = false;
        ApplyButton.Disabled = false;
    }

    public void EditChannelShort(ChatSelectChannel newChannel, int index)
    {
        _shorts[index].Channel = newChannel;
        _changed = true;

        DefaultButton.Disabled = false;
        ApplyButton.Disabled = false;
    }

    public void AddShort(Short newShort)
    {
        _shorts.Add(newShort);
        PopulateShorts();

        DefaultButton.Disabled = false;
        ApplyButton.Disabled = false;
    }

    private void PopulateShorts()
    {
        ShortsContainer.RemoveAllChildren();

        bool ShouldDisplayShort(Short _short)
        {
            if (_searchText == string.Empty)
                return true;

            var optionText = _short.Trigger;

            if (optionText.StartsWith(_searchText, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            if (optionText.Contains(_searchText, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            if (FuzzySearching.LevensteinAlgorithm(_searchText, optionText) < 2)
            {
                return true;
            }

            return false;
        }


        void AddShort(Short _short, int index)
        {
            if (!ShouldDisplayShort(_short))
                return;

            var control = new ShortControl(this, _short, index);
            ShortsContainer.AddChild(control);
        }

        for (int i = 0; i < _shorts.Count; i++)
        {
            AddShort(_shorts[i], i);
        }

  
    }


    public sealed class ShortControl : Control
    {
        public readonly LineEdit TrigerEdit;
        public readonly LineEdit ReactionEdit;
        public readonly Button ChatButton;
        public readonly Button DeleteButton;
        private int _index;

        public Short ChatsanShort;



        public ShortControl(ChatsanPlusTab parent, Short _short, int index)
        {
            _index = index;
            ChatsanShort = _short;

            TrigerEdit = new LineEdit()
            {
                Margin = new Thickness(10,0,20,0),
                Text = _short.Trigger,
                MinWidth = 100
            };

            ReactionEdit = new LineEdit()
            {
                Text = _short.Reaction,
                HorizontalExpand = true,
                MinWidth = 250
            };

            ChatButton = new Button {
                StyleClasses = {
                    StyleBase.ButtonOpenBoth
                },
                MinWidth = 50,
                Margin = new Thickness(20, 0, 30, 0)
            };

            if (ChatsanShort.Channel == ChatSelectChannel.Local)
                ChatButton.Text = "Рядом";
            else
                ChatButton.Text = "Эмоция";

            DeleteButton = new Button { Text = "Х", StyleClasses = { StyleBase.ButtonCaution } };

            var hBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(10,20,0,10),
                Children =
                    {
                        DeleteButton,
                        new Control {MinSize = new Vector2(5, 0)},
                        new Label() { Text = "Ввод:"},
                        TrigerEdit,
                        new Label() { Text = "Вывод:", Margin = new Thickness(0, 0, 5, 0)},
                        ReactionEdit,
                        new Control {MinSize = new Vector2(5, 0)},
                        ChatButton
                    }
            };


            ChatButton.OnPressed += args =>
            {
                if (ChatsanShort.Channel == ChatSelectChannel.Local)
                {
                    ChatsanShort.Channel = ChatSelectChannel.Emotes;
                    ChatButton.Text = "Эмоция";
                }
                else
                {
                    ChatsanShort.Channel = ChatSelectChannel.Local;
                    ChatButton.Text = "Рядом";
                }

                parent.EditChannelShort(ChatsanShort.Channel, _index);

            };

            TrigerEdit.OnTextChanged += _ =>
            {
                parent.EditTrigerShort(_.Text, index);
            };

            ReactionEdit.OnTextChanged += _ =>
            {

                parent.EditReactionShort(_.Text, index);
            };


            DeleteButton.OnPressed += args =>
            {
                parent.RemoveShort(_index);
            };

            AddChild(hBox);
        }
    }


}
