# DHS Captain

- type: job
  id: DHSCaptain
  name: капитан ДВБ
  description: job-description-navy-captain
  playTimeTracker: JobDHSCaptain
  setPreference: false
  startingGear: DHSCaptainGear
  icon: "JobIconDHSCaptain"
  supervisors: job-supervisors-null
  canBeAntag: false
  requirements:
    - !type:AgeRequirement
      requiredAge: 21
  accessGroups:
    - AllAccess
  access:
    - CentralCommand
    - NanotrasenRepresentative
    - BlueshieldOfficer
  special:
    - !type:AddImplantSpecial
      implants:
        [
          MindShieldImplant,
          FreedomImplant,
          BluespaceLifelineImplant,
          RadioImplantCentcomm,
          NutrimentPumpImplant,
          StypticStimulatorImplant,
          SpaceProofImplant,
        ]

# DHS Officer

- type: job
  id: DHSOfficer
  name: офицер ДВБ
  description: job-description-navy-officer
  playTimeTracker: JobDHSOfficer
  setPreference: false
  startingGear: DHSOfficerGear
  icon: "JobIconDHS"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - AllAccess
  access:
    - CentralCommand
    - NanotrasenRepresentative
    - BlueshieldOfficer
  special:
    - !type:AddImplantSpecial
      implants:
        [
          MindShieldImplant,
          FreedomImplant,
          BluespaceLifelineImplant,
          RadioImplantCentcomm,
          NutrimentPumpImplant,
          StypticStimulatorImplant,
        ]

# DHS Ops

- type: job
  id: DHSOps
  name: оперативник ДВБ
  description: job-description-navy-officer
  playTimeTracker: JobDHSOps
  setPreference: false
  startingGear: DHSOpsGear
  icon: "JobIconDHS"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - AllAccess
  access:
    - CentralCommand
    - NanotrasenRepresentative
    - BlueshieldOfficer
  special:
    - !type:AddImplantSpecial
      implants:
        [
          MindShieldImplant,
          FreedomImplant,
          BluespaceLifelineImplant,
          RadioImplantCentcomm,
          NutrimentPumpImplant,
          StypticStimulatorImplant,
        ]

# DHS Ops EVA

- type: job
  id: DHSOpsEVA
  name: оперативник ДВБ
  description: job-description-navy-officer
  playTimeTracker: JobDHSOpsEVA
  setPreference: false
  startingGear: DHSOpsGearEVA
  icon: "JobIconDHS"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - AllAccess
  access:
    - CentralCommand
    - NanotrasenRepresentative
    - BlueshieldOfficer
  special:
    - !type:AddImplantSpecial
      implants:
        [
          MindShieldImplant,
          FreedomImplant,
          BluespaceLifelineImplant,
          RadioImplantCentcomm,
          NutrimentPumpImplant,
          StypticStimulatorImplant,
        ]
